export const MENU_CONFIG = {
  home: { image: require("@/assets/images/home/xiansuo.png"), text: "首页", link: "/" },
  mapSearch: { image: require("@/assets/images/home/baojia.png"), text: "地图搜索", link: "/map/search" },
  MapNavigation: { image: require("@/assets/images/home/renwu.png"), text: "地图导航", link: "/map/navigation" },
  camera: { image: require("@/assets/images/home/baojia.png"), text: "扫码", link: "/camera/scan" },
  photo: { image: require("@/assets/images/home/chuche.png"), text: "拍照", link: "/camera/photo" },
  // bidding: { image: require("@/assets/images/home/baojia.png"), text: "报价管理", link: "/bidding" },
  // delivery: { image: require("@/assets/images/home/chuche.png"), text: "出车计划", link: "/delivery" },
  // clue: { image: require("@/assets/images/home/xiansuo.png"), text: "线索管理", link: "/clue" },
  // task: { image: require("@/assets/images/home/renwu.png"), text: "出车任务", link: "/task" },
  // outTask: { image: require("@/assets/images/home/waiburenwu.png"), text: "外部任务", link: "/outTask" },
  // customerTask: { image: require("@/assets/images/home/order.png"), text: "异常管理", link: "/customerTask" },
  // exception: { image: require("@/assets/images/home/yichang.png"), text: "客户任务", link: "/exception" },
  // approval: { image: require("@/assets/images/home/shenpi.png"), text: "审批管理", link: "/approval" },
  // deliveryApproval: { image: require("@/assets/images/home/yunli.png"), text: "运力审核", link: "/deliveryApproval" },
  // otherFee: { image: require("@/assets/images/home/otherFee.png"), text: "其他费用", link: "/otherFee" },
  // feederException: { image: require("@/assets/images/home/feederException.png"), text: "支线异常监控", link: "/feederException" },
  // feederTask: { image: require("@/assets/images/home/feederList.png"), text: "GroundB任务", link: "/feederTask" },
  // shunluTask: { image: require("@/assets/images/home/feederList.png"), text: "顺陆B任务", link: "/shunluTask" },
  // feederHandoverTask: { image: require("@/assets/images/home/feederHandOver.png"), text: "二程接驳任务", link: "/feederHandoverTask" },
} as const;
